### ISSUE TITLE
Drop org.kde.* when Electron >=23.3.0 is used

### ISSUE THREAD

**Issue by bbhtt** [flathub/com.qq.QQmusic#13]
I can't seem to download the deb due to the domain being blocked in my country or something else. But org.kde.* is no longer required with newer Electron and runtime

https://docs.flatpak.org/en/latest/desktop-integration.html#statusnotifier
    
> Most implementations of StatusNotifer have dropped this requirement
> but known exceptions to this are Electron versions older than 23.3.0.

**Comment by wsgalaxy** [comment]
Fixed in #19 .
