### ISSUE TITLE
无法显示中文字体

### ISSUE THREAD

**Issue by ret2void** [flathub/com.qq.QQmusic#14]
操作系统：Fedora 38
桌面环境：Gnome 44
问题描述：系统已经安装过noto sans cjk系列字体，而后通过flatpak安装qqmusic，无法显示中文字体。
打开qqmusic对host所有文件的访问权限，依然无法正常显示。
截图：
![图片](https://github.com/flathub/com.qq.QQmusic/assets/83763549/844d2abe-f28d-4c0b-8d30-ba4829a2ff9c)

**Comment by pugaizai** [comment]
试试#10

**Comment by chenyuanrun** [comment]
安装非vf版本的字体：
```
dnf install google-noto-sans-cjk-fonts google-noto-serif-cjk-fonts
```
进app内删除fontconfig缓存：
```
flatpak run --command=bash com.qq.QQmusic

rm -rvf ~/.var/app/com.qq.QQmusic/cache/fontconfig/
fc-cache -f -v
```
现在中文应该可以正常显示了。

参考：https://github.com/flathub/com.valvesoftware.Steam/issues/1070#issuecomment-1542667378
